### ISSUE TITLE
`defmemoize` has wrong `indent` for argument list

### ISSUE THREAD

**Issue by Alexander-Shukaev** [skeeto/emacs-memoize#15]
Try to wrap argument list to the next line like this

```
(defmemoize foo
  (&optional xxx)
  "..."
  ...)
```

and you will see that, after indentation, instead of 4 spaces, the argument list is only indented by 2.

**Comment by skeeto** [comment]
You're right, thanks. I wonder if this is a bug in Emacs. The defmemoize 
macro used "indent defun" since it's shaped like "defun". However, both 
defun and cl-defun use "indent 2" which has different behavior. I'd 
expect "indent defun" to have the stylistically correct behavior in this 
case.

**Comment by Alexander-Shukaev** [comment]
Wow, that was quick!  Thank you.  :+1:

**Comment by Alexander-Shukaev** [comment]
Right, that was a weird thing I also noticed quite some time ago.  Not sure if it's a bug, perhaps a misfeature that is stuck due to history.  Curiously, I have the following in my configuration:

```
./.emacs.d/init/init-lisp-mode.el:10:  (put 'defsubst     'lisp-indent-function 2)
./.emacs.d/lisp/devil/devil-common.el:34:(put 'evil-define-command 'lisp-indent-function 2)
./.emacs.d/lisp/devil/devil-macros.el:6:(put 'evil-define-motion      'lisp-indent-function 2)
./.emacs.d/lisp/devil/devil-macros.el:7:(put 'evil-define-text-object 'lisp-indent-function 2)
./.emacs.d/lisp/devil/devil-macros.el:8:(put 'evil-define-operator    'lisp-indent-function 2)

```
