### ISSUE TITLE
De-memoize function?

### ISSUE THREAD

**Issue by alphapapa** [skeeto/emacs-memoize#7]
Hi Chris,

What do you think about adding a function to de-memoize memoized functions?  I'm thinking about using memoize with magit-todos to cache a magit function call, but I'd like to only do that when the minor mode is activated, and then de-memoize it when the mode is deactivated, so as not to permanently interfere with magit.

**Comment by skeeto** [comment]
I suppose the original function could be stashed away in the symbol 
plist (e.g. :memoize-original-function). Should be pretty simple.

**Comment by alphapapa** [comment]
Yeah, that's what I was thinking.  Should I send a PR to save you a little time?

**Comment by skeeto** [comment]
Sure. Since I don't actually use this library I wasn't intending on 
doing anything myself anyway.

**Comment by alphapapa** [comment]
LOL, fair enough.
